<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Environment.props" Condition="Exists('..\..\Environment.props')" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SharedDiscovery.Core\SharedDiscovery.Core.csproj" SetTargetFramework="TargetFramework=net8.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(VALHEIM_INSTALL)\valheim_Data\Managed\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
